server:
  port: 8761

spring:
  thymeleaf:
    enabled: false
  freemarker:
    enabled: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: discovery-server
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
    status-page-url: http://${eureka.instance.hostname}:${server.port}/admin/info
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
