server:
  port: 9000

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: uaa-server
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    
#LIQUIBASE
spring:
  liquibase:
    change-log: classpath:liquibase/base.xml
    
#H2

  h2:
    console:
      enabled: true
      path: /h2-console


#DATABSE
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:file:~/uaadb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

